### ISSUE TITLE
Dig through current code

### ISSUE THREAD

**Issue by annashiheart** [CMU-313/nodebb-f24-boba#3]
**Effort**: 3 hrs
**Dependencies**: None
**Acceptance Criteria**: Identify files where this may be involved, get UI working

**Comment by annashiheart** [comment]
Effort: 3 hrs
Dependencies: None
Acceptance Criteria: Identify files where this may be involved, point to areas in code

**Comment by AliceeLe** [comment]
From our understanding, we will modify the fields in the database through yaml files, located in `public/openapi`. Furthermore, the starting point is `app.js`. Since we want to add a new feature, answered by professor, that is similar to unread, we will add new functionalities into the `src/component` directory, then updating `app.js` to update the API endpoints.
